import asyncio
import os
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

async def generate_report():
    uri = os.getenv("MONGODB_URL")
    db_name = os.getenv("MONGODB_DB_NAME", "chareli_ai")
    
    print(f"Connecting to MongoDB to generate sync report...")
    client = AsyncIOMotorClient(uri)
    try:
        db = client[db_name]
        collection = db["game_summaries"]
        
        # Get count
        total_docs = await collection.count_documents({})
        
        # Get sample of 5 documents
        cursor = collection.find().limit(5)
        samples = await cursor.to_list(length=5)
        
        report_path = "sync_report.md"
        with open(report_path, "w") as f:
            f.write("# Phase 1 Sync Report: PG Metadata to MongoDB Atlas\n\n")
            f.write(f"**Total Documents Synced:** {total_docs}\n")
            f.write(f"**Target Database:** `{db_name}`\n")
            f.write(f"**Target Collection:** `game_summaries`\n\n")
            f.write("## Sample Synced Data (Top 5)\n\n")
            f.write("| PG ID | Title | Summary Excerpt | Last Synced |\n")
            f.write("| :--- | :--- | :--- | :--- |\n")
            
            for doc in samples:
                summary = doc.get("summary", "")
                excerpt = (summary[:75] + '...') if len(summary) > 75 else summary
                f.write(f"| `{doc.get('pg_id')}` | **{doc.get('title')}** | {excerpt} | {doc.get('last_synced')} |\n")
            
            f.write("\n\n---\n*Generated by SEO Content Agent - Phase 1*")
            
        print(f"\n✅ Report generated successfully: {report_path}")
        print(f"You can now open '{report_path}' to view and share the results!")
        
    except Exception as e:
        print(f"❌ Failed to generate report: {e}")
    finally:
        client.close()

if __name__ == "__main__":
    asyncio.run(generate_report())
