import os
from dotenv import load_dotenv
from tavily import TavilyClient

# Load the environment variables to pick up the API key from .env
load_dotenv()

def test_tavily_search():
    api_key = os.getenv("TAVILY_API_KEY")
    if not api_key:
        print("Error: TAVILY_API_KEY clearly not found in environment variables.")
        return

    print("Initializing TavilyClient...")
    client = TavilyClient(api_key=api_key)

    query = "Best retro arcade boxing games"
    print(f"Executing search for: '{query}'...")
    
    # We use advanced search to get snippet data for our SEO agent
    response = client.search(
        query=query,
        search_depth="advanced",
        include_raw_content=True
    )
    
    print("\n--- Search Results ---")
    print(f"Answer generated by Tavily: {response.get('answer', 'No answer provided')}")
    print("\nTop Articles Found:")
    for result in response.get('results', []):
        print(f"- {result['title']} ({result['url']})")
        print(f"  Score: {result.get('score')}")
        
    print("\nRaw JSON Response Structure Preview:")
    import json
    # Print a truncated version of the raw JSON to understand the data shape we will pass to the LLM
    print(json.dumps(response, indent=2)[:500] + "\n...[truncated]...")

if __name__ == "__main__":
    test_tavily_search()
